// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TimelineCache is an autogenerated mock type for the TimelineCache type
type TimelineCache struct {
	mock.Mock
}

// InvalidateTimeline provides a mock function with given fields: ctx, userID
func (_m *TimelineCache) InvalidateTimeline(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateTimeline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTimelineCache creates a new instance of TimelineCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTimelineCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *TimelineCache {
	mock := &TimelineCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
