// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	tweet "github.com/oscarsalomon89/go-hexagonal/internal/application/tweet"
	mock "github.com/stretchr/testify/mock"
)

// TweetReader is an autogenerated mock type for the TweetReader type
type TweetReader struct {
	mock.Mock
}

// GetTweetsByUserIDs provides a mock function with given fields: ctx, userIDs, limit, offset
func (_m *TweetReader) GetTweetsByUserIDs(ctx context.Context, userIDs []string, limit int, offset int) ([]tweet.Tweet, error) {
	ret := _m.Called(ctx, userIDs, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetTweetsByUserIDs")
	}

	var r0 []tweet.Tweet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, int, int) ([]tweet.Tweet, error)); ok {
		return rf(ctx, userIDs, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, int, int) []tweet.Tweet); ok {
		r0 = rf(ctx, userIDs, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tweet.Tweet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, int, int) error); ok {
		r1 = rf(ctx, userIDs, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTweetReader creates a new instance of TweetReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTweetReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *TweetReader {
	mock := &TweetReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
