// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	tweet "github.com/oscarsalomon89/go-hexagonal/internal/application/tweet"
	mock "github.com/stretchr/testify/mock"
)

// TweetCreator is an autogenerated mock type for the TweetCreator type
type TweetCreator struct {
	mock.Mock
}

// CreateTweet provides a mock function with given fields: ctx, _a1
func (_m *TweetCreator) CreateTweet(ctx context.Context, _a1 *tweet.Tweet) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateTweet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *tweet.Tweet) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTweetCreator creates a new instance of TweetCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTweetCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TweetCreator {
	mock := &TweetCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
